# Generated by Django 3.0.5 on 2020-05-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_id', models.CharField(max_length=12)),
                ('pr_title', models.CharField(max_length=50)),
                ('pr_description', models.CharField(max_length=200)),
                ('pr_manufacturer', models.CharField(max_length=30)),
                ('pr_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
