# Generated by Django 3.0.5 on 2020-05-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pr_description',
            field=models.CharField(max_length=15000),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_title',
            field=models.CharField(max_length=100),
        ),
    ]
