# Generated by Django 3.0.5 on 2020-05-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pr_description',
            field=models.CharField(max_length=100, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_id',
            field=models.CharField(max_length=30, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_manufacturer',
            field=models.CharField(max_length=30, verbose_name='manufacturer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_title',
            field=models.CharField(max_length=30, verbose_name='title'),
        ),
    ]
