# Generated by Django 3.0.5 on 2020-05-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200530_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pr_description',
            field=models.CharField(max_length=15000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
