# Generated by Django 3.0.5 on 2020-06-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200601_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='inbasket',
            field=models.BooleanField(default=True),
        ),
    ]
